"""
Utility module for the SQL Agent.

This module provides helper classes and functions for the SQL agent,
including a factory for creating LangChain prompts and a data class
for managing the agent's execution context.
"""

from langchain_core.prompts import ChatPromptTemplate  
from langchain_community.utilities import SQLDatabase
from dataclasses import dataclass, field
import time
from typing import List, Optional

class PromptFactory:
    """
    A factory class for creating reusable and parameterized ChatPromptTemplates.
    """

    @classmethod
    def create_db_selection_prompt(cls) -> ChatPromptTemplate:
        """
        Creates a prompt template for selecting the most relevant database.

        Returns:
            ChatPromptTemplate: A prompt template configured to ask the LLM to select
            a database from a provided list based on the user's input.
        """
        system_message = ('你是一個善於將使用者問題連結到正確資料庫的專家。'
                        '根據使用者問題和可用的資料庫名稱列表，你必須選擇最相關的單一資料庫。')
        user_message = ('使用者問題: "{input}"\n'
                        '可用資料庫: {db_names}\n'
                        '請僅回應列表中最相關的資料庫名稱，不要添加額外解釋，不要用Markdown語法。')
        return cls._create_prompt(system_message, user_message)
    
    @staticmethod
    def _create_prompt(system_message: str, user_message: str) -> ChatPromptTemplate:
        """
        Helper method to create a ChatPromptTemplate from system and user messages.

        Args:
            system_message (str): The system instruction message.
            user_message (str): The user input message template.

        Returns:
            ChatPromptTemplate: The constructed chat prompt template.
        """
        return ChatPromptTemplate.from_messages([
            ('system', system_message),
            ('user', user_message)
        ])

    @classmethod
    def create_sql_generation_prompt(cls) -> ChatPromptTemplate:
        """
        Creates a prompt template for generating SQL queries.

        Returns:
            ChatPromptTemplate: A prompt template configured to ask the LLM to generate
            a SQL query based on the database schema and user input.
        """
        system_message = '請根據提供的SQL資料庫結構與範例，生成SQL的查詢語法: {db_schema}{schema_description}'
        user_message = ('使用者提問: "{input}"。\n請根據以下規則生成SQL查詢語法: '
                        '只生成SQL語法，不要添加額外解釋，不要用Markdown語法包裝SQL語法')
        return cls._create_prompt(system_message, user_message)

    @classmethod
    def create_sql_correction_prompt(cls) -> ChatPromptTemplate:
        """
        Creates a prompt template for correcting failed SQL queries.

        Returns:
            ChatPromptTemplate: A prompt template configured to ask the LLM to fix
            a failing SQL query using error information and schema details.
        """
        system_message = '你之前生成了一個SQL查詢，但執行失敗了。請根據提供的SQL資料庫結構、原始使用者提問、失敗的SQL查詢以及錯誤訊息，生成一個修正後的SQL查詢語法。'
        user_message = ('原始使用者提問: "{input}"\n'
                        'SQL資料庫結構: {db_schema}\n'
                        '失敗的SQL查詢: "{failing_query}"\n'
                        '錯誤訊息: "{error_message}"\n'
                        '請根據以上資訊，生成修正後的SQL查詢語法。只生成SQL語法，不要添加額外解釋，不要用Markdown語法包裝SQL語法。')
        return cls._create_prompt(system_message, user_message)

    @classmethod
    def create_answer_generation_prompt(cls) -> ChatPromptTemplate:
        """
        Creates a prompt template for generating the final natural language answer.

        Returns:
            ChatPromptTemplate: A prompt template configured to generate a natural
            language response based on the SQL query result.
        """
        template = ("請根據以下資訊生成自然語言回應：\n"
                    "- 問題: {input}\n"
                    "- SQL 查詢: {query}\n"
                    "- 查詢結果: {result}\n\n"
                    "請提供簡潔有、具有說明性的回應。")
        return ChatPromptTemplate.from_template(template)

@dataclass
class SQLAgentContext:
    """
    A data class to hold the context passed through the SQL agent chain.

    Attributes:
        user_input (str): The original question asked by the user.
        schema_description (str): A description of the database schema.
        start_time (float): The timestamp when the context was initialized.
        db_names (List[str]): A list of available database names.
        db_path (str): The file path to the selected database.
        db (Optional[SQLDatabase]): The connected SQLDatabase instance.
        db_schema (str): The schema information of the selected database.
        query (str): The generated SQL query.
        result (str): The result of the SQL query execution.
        final_response (str): The final natural language response generated by the LLM.
    """
    # Initial inputs
    user_input: str
    schema_description: str
    start_time: float = field(default_factory=time.time)
    db_names: List[str] = field(default_factory=list)

    # Fields populated during the chain
    db_path: str = ""
    db: Optional[SQLDatabase] = None
    db_schema: str = ""
    query: str = ""
    result: str = ""
    final_response: str = ""
